[Language_en]
Name=Farollo's Cursed Vehicle Kitbashes
Description=No, I guess ill go die
[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept a higher PATCH.
;Would recommend this as a default for starters.
ApproximateVersion=0.8.0