[8in/55_mk16]
HorizontalDegreesPerSecond=5   // rotation speed horizontally
VerticalDegreesPerSecond=8.2     // rotation speed vertically
FireRate=100                     // rounds per minute
RoundsLoaded=3                         
ReloadTime=6                          
RecoilTime=0.4                 // time in seconds for the recoil
RecoilStrength=0.0005           // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/B-13_130mm_fire_emitter
#EffectPosition=-0.0154,0,0.129|0.0154,0,0.129
EffectPosition=-0.0154,0,0.11|0.0154,0,0.11
SpawnPosition=-0.0154,0,0.088|0.0154,0,0.088
FireSequential=True            //REQUIRED for burst fire
ModuleType=MediumTurret