[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
ASWNuke=Nuclear Depth Charge
LaserDesignator=Laser Designator (Iowa Fire Support)
Phoenix=1x AIM-54A
NuclearAttack=B41 Thermonuclear Bomb

